package users;

public class DeansOffice extends Employee {

	private static final long serialVersionUID = 1L;
	private Manager manager;
    public String meetingTitle;
    public String meetingDate;
    public String meetingTime;
    public String requestDescription;
    public String reportTitle;
    
    public Manager getManager() {
        return this.manager;
    }
    public void setManager(Manager manager) {
        this.manager = manager;
    }
  //don't know if this getters and setters necessary
	public String getMeetingTitle() {
		return meetingTitle;
	}
	public void setMeetingTitle(String meetingTitle) {
		this.meetingTitle = meetingTitle;
	}
	public String getMeetingDate() {
		return meetingDate;
	}
	public void setMeetingDate(String meetingDate) {
		this.meetingDate = meetingDate;
	}
	public String getMeetingTime() {
		return meetingTime;
	}
	public void setMeetingTime(String meetingTime) {
		this.meetingTime = meetingTime;
	}
	public String getRequestDescription() {
		return requestDescription;
	}
	public void setRequestDescription(String requestDescription) {
		this.requestDescription = requestDescription;
	}
	public String getReportTitle() {
		return reportTitle;
	}
	public void setReportTitle(String reportTitle) {
		this.reportTitle = reportTitle;
	}
    
	
	
	
    //                          Operations      
    
    // Method to assign a task to the manager
    public void assignTaskToManager(String taskDescription) {
        if (manager != null) {
            manager.performTask(taskDescription);
        } else {
            System.out.println("No manager assigned to the Dean's office. Cannot assign task.");
        }
    }

    // Method to schedule a meeting for the Dean's office
    public void scheduleMeeting(String meetingTitle, String meetingDate, String meetingTime) {
        System.out.println("Meeting scheduled by the Dean's office:");
        System.out.println("Title: " + meetingTitle);
        System.out.println("Date: " + meetingDate);
        System.out.println("Time: " + meetingTime);
    }

    // Method to approve a request
    public void approveRequest(String requestDescription) {
        System.out.println("Request approved by the Dean's office: " + requestDescription);
    }
    
    

    // Method to generate a report
    public void generateReport(String reportTitle) {
        System.out.println("Report generated by the Dean's office: " + reportTitle);
    }
    
    
    
    
    //don't know if this String method necessary
	@Override
	public String toString() {
		return "DeansOffice [manager=" + manager + ", meetingTitle=" + meetingTitle + ", meetingDate=" + meetingDate
				+ ", meetingTime=" + meetingTime + ", requestDescription=" + requestDescription + ", reportTitle="
				+ reportTitle + "]";
	}
}
